# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe5fb6b656a834d64e4964671d8cadfa"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "openletterconnect"
handle = "openletterconnect"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "olc-develop.myshopify.com"
